language: python

python:
  - 3.5

install:
  - pip install -r requirements-test.txt
  - pip install -r requirements.txt

script:
  - nosetests
  - coverage run --source=tutorial_test setup.py test

after_success:
  - coveralls
